const fs = require("fs");
const path = require("path");
const { pathToFileURL } = require("url");
const { toLuaLongString } = require("./luaString.js");
const { randomInt } = require("crypto");

// --- Resolve paths -----------------------------------------------------------
const srcRoot = path.resolve(__dirname, "../Prometheus");

const PRESETS = Object.freeze(["Minify", "Weak", "Medium", "Strong", "Extreme"]);
const LUA_VERSIONS = Object.freeze(["Lua51", "LuaU"]);

// --- Lua file discovery ------------------------------------------------------
function findLuaFiles(dir) {
  const results = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const absolute = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...findLuaFiles(absolute));
    } else if (entry.isFile() && entry.name.endsWith(".lua")) {
      results.push(absolute);
    }
  }
  return results;
}

/** Convert a file path to a Lua module name (e.g. "src/prometheus/pipeline.lua" → "prometheus.pipeline") */
function luaPathToModuleName(filePath) {
  const normalized = filePath.split(path.sep).join("/");
  const withoutSrc = normalized.replace(/^src\//, "");
  return withoutSrc.replace(/\.lua$/, "").split("/").join(".");
}

/** Build the bootstrap Lua code that preloads every Prometheus source file via package.preload */
function buildBootstrapLua() {
  const luaFiles = findLuaFiles(srcRoot);

  const chunks = luaFiles.map((absolute) => {
    const relative = path.relative(srcRoot, absolute);
    const moduleName = luaPathToModuleName(path.join("src", relative));
    const source = fs.readFileSync(absolute, "utf8");
    const chunkName = `@/src/${relative.split(path.sep).join("/")}`;

    // Use quoted string for the module name key to avoid ambiguity
    // between [[ (long string) and [ (table index) at the lexer level.
    const safeModuleName = moduleName
      .replace(/\\/g, "\\\\")
      .replace(/"/g, '\\"')
      .replace(/\n/g, "\\n");

    // For the source code, use long string with minimum 1 equals sign
    // so it never starts with [[ after [ or ( context
    return `
package.preload["${safeModuleName}"] = function(...)
  local chunk, err = load(${toLuaLongString(source, 1)}, ${toLuaLongString(chunkName, 1)}, "t")
  if not chunk then
    error(err)
  end
  return chunk(...)
end`;
  });

  return chunks.join("\n");
}

/** Build the Lua script that runs Prometheus with the given options */
const WATERMARK = "-- ts file was generated by Stealth-X Obfuscator\n\n";

let bootstrapLuaCache = null;

function getBootstrapLua() {
  if (bootstrapLuaCache === null) {
    bootstrapLuaCache = buildBootstrapLua();
  }
  return bootstrapLuaCache;
}

/** Build the Lua script that runs Prometheus with the given options */
function buildRunLua(options) {
  const bootstrap = getBootstrapLua();

  return `
_G.arg = _G.arg or {}
${bootstrap}

local logs = {}
local unpackFn = table.unpack or unpack
local function pushLog(level, ...)
  local parts = {}
  for i = 1, select("#", ...) do
    parts[#parts + 1] = tostring(select(i, ...))
  end
  if type(_G.__prometheusPushLog) == "function" then
    _G.__prometheusPushLog(level, unpackFn(parts))
  end
  logs[#logs + 1] = { level = level, message = table.concat(parts, " ") }
end

if not math.log10 then
  math.log10 = function(value)
    return math.log(value, 10)
  end
end

local Prometheus = require("prometheus")
Prometheus.Logger.logLevel = Prometheus.Logger.LogLevel.Info
Prometheus.colors.enabled = false
Prometheus.Logger.debugCallback = function(...) pushLog("debug", ...) end
Prometheus.Logger.logCallback = function(...) pushLog("info", ...) end
Prometheus.Logger.warnCallback = function(...) pushLog("warn", ...) end
Prometheus.Logger.errorCallback = function(...)
  pushLog("error", ...)
  error(table.concat((function(...)
    local parts = {}
    for i = 1, select("#", ...) do
      parts[#parts + 1] = tostring(select(i, ...))
    end
    return parts
  end)(...), " "))
end

local ok, outputOrError = xpcall(function()
  local preset = ${toLuaLongString(options.preset, 1)}
  local source = ${toLuaLongString(options.source, 1)}
  local filename = ${toLuaLongString(options.filename, 1)}
  local config = {}
  for key, value in pairs(Prometheus.Presets[preset]) do
    config[key] = value
  end

  config.LuaVersion = ${toLuaLongString(options.luaVersion, 1)}
  config.PrettyPrint = ${options.prettyPrint ? "true" : "false"}
  config.Seed = ${Math.max(1, Math.floor(options.seed))}

  return Prometheus.Pipeline:fromConfig(config):apply(source, filename)
end, debug.traceback)

return { ok = ok, output = ok and outputOrError or "", error = ok and "" or outputOrError, logs = logs }
`;
}

function normalizeLogs(logs) {
  if (!Array.isArray(logs)) {
    return [];
  }
  return logs.map((entry) => {
    const candidate = entry;
    return {
      level:
        candidate.level === "warn" ||
          candidate.level === "error" ||
          candidate.level === "debug"
          ? candidate.level
          : "info",
      message: String(candidate.message ?? ""),
    };
  });
}

// Keep the Wasmoon module/factory warm between jobs.
// The expensive WASM setup is shared, while each request still gets its own
// Lua engine so state cannot leak between users.
let LuaFactoryCtor = null;
let sharedLuaFactory = null;
let wasmoonLoadPromise = null;

async function ensureWasmoonLoaded() {
  if (sharedLuaFactory) return sharedLuaFactory;
  if (wasmoonLoadPromise) return wasmoonLoadPromise;

  wasmoonLoadPromise = (async () => {
    const mod = await import("wasmoon");
    const factoryCtor =
      typeof mod?.LuaFactory === "function"
        ? mod.LuaFactory
        : typeof mod?.default?.LuaFactory === "function"
          ? mod.default.LuaFactory
          : null;

    if (!factoryCtor) {
      throw new Error("Unable to resolve LuaFactory from wasmoon");
    }

    LuaFactoryCtor = factoryCtor;
    const gluePath = require.resolve("wasmoon/dist/glue.wasm");
    sharedLuaFactory = new LuaFactoryCtor(pathToFileURL(gluePath).href);
    return sharedLuaFactory;
  })();

  try {
    return await wasmoonLoadPromise;
  } catch (error) {
    wasmoonLoadPromise = null;
    throw error;
  }
}

/**
 * Run Prometheus obfuscation on the given Lua source code.
 * Uses wasmoon to execute Prometheus (Lua) in a sandboxed Lua engine.
 *
 * @param {object} options
 * @param {string} options.source
 * @param {string} options.filename
 * @param {"Minify"|"Weak"|"Medium"|"Strong"|"Extreme"} options.preset
 * @param {"Lua51"|"LuaU"} options.luaVersion
 * @param {boolean} options.prettyPrint
 * @param {number} options.seed
 * @returns {Promise<{ok: boolean, output: string, error: string, logs: Array<{level: string, message: string}>}>}
 */
async function runPrometheus(options = {}) {
  const logs = [];
  let lua = null;

  try {
    options = {
      ...options,
      preset: !options.preset || options.preset === "Roblox" ? "Medium" : options.preset,
      luaVersion: options.luaVersion ?? "LuaU",
      filename: options.filename ?? "input.lua",
      seed: options.seed ?? randomInt(1, 2147483647),
    };
    if (!PRESETS.includes(options.preset)) throw new Error("Invalid preset: " + options.preset);
    if (!LUA_VERSIONS.includes(options.luaVersion)) throw new Error("Invalid Lua version: " + options.luaVersion);
    if (typeof options.source !== "string") throw new Error("source must be a string");
    if (!Number.isSafeInteger(options.seed) || options.seed < 1) throw new Error("seed must be a positive safe integer");
    const factory = await ensureWasmoonLoaded();
    lua = await factory.createEngine({ openStandardLibs: true });

    // Set up log capture
    if (typeof lua.global.set === "function") {
      lua.global.set("__prometheusPushLog", (level, ...parts) => {
        logs.push({
          level: level === "warn" || level === "error" || level === "debug" ? level : "info",
          message: parts.map((p) => String(p)).join(" "),
        });
      });
    }

    const result = await lua.doString(buildRunLua(options));

    if (result && result.ok === false) {
      return {
        ok: false,
        error: String(result.error ?? "Prometheus failed"),
        logs: normalizeLogs(result.logs),
      };
    }

    return {
      ok: true,
      output: WATERMARK + String(result?.output ?? ""),
      logs: normalizeLogs(result?.logs),
    };
  } catch (error) {
    return {
      ok: false,
      error: error instanceof Error ? error.message : String(error),
      logs,
    };
  } finally {
    if (lua && typeof lua.global.close === "function") {
      lua.global.close();
    }
  }
}

module.exports = { runPrometheus, PRESETS, LUA_VERSIONS };
